version: "3.3"

services:
  qix-engine:
    image: qlikcore/engine:12.925.0
    restart: always
    command: |
      -S AcceptEULA=${ACCEPT_EULA} -S DisableWSOriginCheck=1
    ports:
      - 9076:9076
      